<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>name</key>
    <string>JavaScript</string>
    <key>scopeName</key>
    <string>source.js</string>
    <key>fileTypes</key>
    <array>
        <string>js</string>
        <string>mjs</string>
        <string>cjs</string>
    </array>
    <key>patterns</key>
    <array>
        <dict><key>include</key><string>#comments</string></dict>
        <dict><key>include</key><string>#strings</string></dict>
        <dict><key>include</key><string>#keywords</string></dict>
        <dict><key>include</key><string>#constants</string></dict>
        <dict><key>include</key><string>#numbers</string></dict>
        <dict><key>include</key><string>#functions</string></dict>
        <dict><key>include</key><string>#operators</string></dict>
        <dict><key>include</key><string>#punctuation</string></dict>
    </array>
    <key>repository</key>
    <dict>
        <key>comments</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>name</key><string>comment.line.double-slash.js</string>
                    <key>match</key><string>//.*$</string>
                </dict>
                <dict>
                    <key>name</key><string>comment.block.js</string>
                    <key>begin</key><string>/\*</string>
                    <key>end</key><string>\*/</string>
                </dict>
            </array>
        </dict>
        <key>strings</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>name</key><string>string.quoted.double.js</string>
                    <key>begin</key><string>"</string>
                    <key>end</key><string>(?&lt;!\\)"</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>name</key><string>constant.character.escape.js</string>
                            <key>match</key><string>\\.</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>name</key><string>string.quoted.single.js</string>
                    <key>begin</key><string>'</string>
                    <key>end</key><string>(?&lt;!\\)'</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>name</key><string>constant.character.escape.js</string>
                            <key>match</key><string>\\.</string>
                        </dict>
                    </array>
                </dict>
            </array>
        </dict>
        <key>keywords</key>
        <dict>
            <key>name</key><string>keyword.control.js</string>
            <key>match</key><string>\b(?:async|await|break|case|catch|class|const|continue|default|delete|do|else|export|extends|finally|for|from|function|if|import|in|instanceof|let|new|of|return|static|super|switch|throw|try|typeof|var|void|while|with|yield)\b</string>
        </dict>
        <key>constants</key>
        <dict>
            <key>name</key><string>constant.language.js</string>
            <key>match</key><string>\b(?:true|false|null|undefined|NaN|Infinity|this)\b</string>
        </dict>
        <key>numbers</key>
        <dict>
            <key>name</key><string>constant.numeric.js</string>
            <key>match</key><string>\b(?:0[xX][0-9A-Fa-f]+|\d+(?:\.\d+)?)\b</string>
        </dict>
        <key>functions</key>
        <dict>
            <key>name</key><string>entity.name.function.js</string>
            <key>match</key><string>\b[A-Za-z_$][A-Za-z0-9_$]*(?=\s*\()</string>
        </dict>
        <key>operators</key>
        <dict>
            <key>name</key><string>keyword.operator.js</string>
            <key>match</key><string>[+\-*/%=&amp;|!&lt;&gt;?:~^]+</string>
        </dict>
        <key>punctuation</key>
        <dict>
            <key>name</key><string>punctuation.definition.js</string>
            <key>match</key><string>[()\[\]{}.,;]</string>
        </dict>
    </dict>
</dict>
</plist>

